dyn_obj:
    points_topic: "/cloud_registered_body"
    odom_topic: "/aft_mapped_to_init"
    frame_id: "camera_init"
    pc_topic: "/lidar_top"

    dataset: 1 #0 for kitti, 1 for nuscenes, 2 for waymo, 3 for avia
    map_buffer_delay: 0.1
    buffer_size: 500000
    points_num_perframe: 50000
    depth_map_duration: 0.2
    max_depth_map_num: 5
    max_pixel_points: 5
    lidar_scan_period: 0.05
    self_x_front: 2.2
    self_x_back: -1.2
    self_y_left: 0.7
    self_y_right: -0.7
    lidar_blind_distance: 0.2
    lidar_fov_up: 10.0
    lidar_fov_down: -30.0
    lidar_fov_left: 180.0
    lidar_fov_right: -180.0
    
    case1_enter_threshold_min: 1.0
    case1_enter_threshold_max: 0.3
    case1_depth_consistency_threshold: 0.3
    case1_hor_consistency_threshold: 0.01
    case1_ver_consistency_threshold: 0.03
    case1_hor_consist_factor: 0.15
    case1_ver_consist_factor: 0.15
    case1_success_threshold: 3
    case1_interp_on: true

    case2_velocity_threshold: 1.0
    case2_acc_threshold: 7.0
    case2_depth_consistency_threshold: 0.2
    case2_hor_consistency_threshold: 0.01
    case2_ver_consistency_threshold: 0.03
    case2_depth_occlusion_threshold: 10.15
    case2_hor_occlusion_threshold: 0.01
    case2_ver_occlusion_threshold: 0.04
    case2_depth_depth_consistency_threshold: 0.1
    case2_depth_depth_consist_threshold_max: 0.5
    case2_hor_depth_consist_threshold: 0.01
    case2_ver_depth_consist_threshold: 0.03
    case2_occluded_times_threshold: 3
    case2_k_depth: 0.005
    case2_interp_on: false

    case3_velocity_threshold: 0.5
    case3_acc_threshold: 15.0
    case3_depth_consistency_threshold: 0.2
    case3_hor_consistency_threshold: 0.01
    case3_ver_consistency_threshold: 0.03
    case3_depth_occlusion_threshold: 0.15
    case3_hor_occlusion_threshold: 0.01
    case3_ver_occlusion_threshold: 0.04
    case3_depth_depth_consistency_threshold: 0.3
    case3_depth_depth_consistency_threshold_max: 1.0
    case3_hor_depth_consistency_threshold: 0.01
    case3_ver_depth_consistency_threshold: 0.03
    case3_occlusion_times_threshold: 3
    case3_k_depth: 0.005
    case3_interp_on: false

    interp_hor_threshold: 0.015
    interp_ver_threshold: 0.06
    case1_interp_threshold: 1.5
    case1_interp_start_depth: 15
    interp_kp: 0.15
    interp_kd: 1.5
    case2_interp_threshold: 0.25
    case3_interp_threshold: 0.05

    cluster_coupled: true
    cluster_future: true
    cluster_extend_pixel: 3
    cluster_min_pixel_number: 3

    

    debug_on: false
    
    vertical_resolution: 0.022 #0.022
    horizontal_resolution: 0.007 #0.005
    