dyn_obj:
    points_topic: "/cloud_registered_body"
    odom_topic: "/aft_mapped_to_init"
    frame_id: "camera_init"
    # pc_topic: "/velodyne_points"

    dataset: 0 #0 for kitti, 1 for nuscenes, 2 for waymo, 3 for avia
    use_odom_file: true
    map_buffer_delay: 0.1
    buffer_size: 300000
    points_num_perframe: 150000
    depth_map_duration: 0.1
    max_depth_map_num: 9
    max_pixel_points: 5
    lidar_scan_period: 0.1
    self_x_front: 2.5
    self_x_back: -1.5
    self_y_left: 0 #1.6
    self_y_right: -0 #1.6
    lidar_blind_distance: 0.3
    lidar_fov_up: 2.0
    lidar_fov_down: -23.0
    lidar_fov_left: 180.0
    lidar_fov_right: -180.0
    neighbor_pixel_range: 1
    

    case1_enter_threshold_min: 1.0 # kill car front points (close to wall, related to view change)
    case1_enter_threshold_max: 0.3 # equal to case1_depth_consistency_threshold, for save pedestrain close to wall
    case1_depth_consistency_threshold: 0.3
    case1_hor_consistency_threshold: 0.01
    case1_ver_consistency_threshold: 0.015
    case1_hor_consist_factor: 0.15
    case1_ver_consist_factor: 0.15
    case1_success_threshold: 2
    case1_interp_on: true

    case2_velocity_threshold: 1.0
    case2_acc_threshold: 7.0
    case2_depth_consistency_threshold: 0.2
    case2_hor_consistency_threshold: 0.01
    case2_ver_consistency_threshold: 0.01
    case2_depth_occlusion_threshold: 10.15
    case2_hor_occlusion_threshold: 0.01
    case2_ver_occlusion_threshold: 0.015
    case2_depth_depth_consistency_threshold: 0.1
    case2_depth_depth_consist_threshold_max: 0.5
    case2_hor_depth_consist_threshold: 0.01
    case2_ver_depth_consist_threshold: 0.01
    case2_occluded_times_threshold: 2
    case2_k_depth: 0.005
    case2_interp_on: false

    case3_velocity_threshold: 0.5
    case3_acc_threshold: 15.0
    case3_depth_consistency_threshold: 0.2
    case3_hor_consistency_threshold: 0.01
    case3_ver_consistency_threshold: 0.008
    case3_depth_occlusion_threshold: 0.15
    case3_hor_occlusion_threshold: 0.01
    case3_ver_occlusion_threshold: 0.01
    case3_depth_depth_consistency_threshold: 0.3
    case3_depth_depth_consistency_threshold_max: 1.0
    case3_hor_depth_consistency_threshold: 0.01
    case3_ver_depth_consistency_threshold: 0.01
    case3_occlusion_times_threshold: 2
    case3_interp_on: false

    interp_hor_threshold: 0.015
    interp_ver_threshold: 0.007
    case1_interp_threshold: 0.5
    case1_interp_start_depth: 10
    interp_kp: 0.1
    interp_kd: 0.5
    case2_interp_threshold: 0.25
    case3_interp_threshold: 0.05

    cluster_coupled: true
    cluster_future: true
    cluster_extend_pixel: 2
    cluster_min_pixel_number: 8
    cluster_thrustable_thresold: 0.3
    cluster_Voxel_revolusion: 0.3
    

    debug_on: false
    
    vertical_resolution: 0.007
    horizontal_resolution: 0.005
    